sudo: false
language: python
python:
- 3.7
- 3.6
- 3.5
- 3.4
env:
  global:
  - secure: gc7dsg1G/kVXASt4pBqpWKfwEXF8neAvopxxrDLEA9dHfZOdrK4h/26zzD3rMyrX5idyF42E+0phoMsQ5bNNG7GwrYNShNtmZcTureHm/2Bsd4ZJdhCmCaURSqpp3kQmokJ1ZdeKLzM/UQYbDEOsF0ILCIUeR7zVlyONX0BAYWdtcdvzM3cdluzRBEYS7aMWRBaQMVCkl2t0tqUUObv7TmhwsKuWoDTbI8c/fKxkC+8kxTLBwVcl27WSOavN64pxZl67lrNpXBqiHKpOgxSYn7tMB/Ty1FogzyejLYU+AtC8eAhFEwMy3+2+xO2xLcB5WBDCfu5PgkrNafa9KdhGbjgndQadrvAcJz+7JXifsnYsOS2VE+2FeEQZhz59R6guUgs8dbhSiOlLBbbMbzqlLcukf+6oWILxVgIPwZGX9oOHA2+Zwtdb+kWC4A48o/gAWhyrtnIgHcmseqRerBRrGGlpCcwV85OuBAeCiOqpkB40Blc1o4DBHchRr1pis7e3S9rDESD7Q+9HHX9cgJcR2vY4loTJNfTmYtxhf5axqKZ8cGOeLFfVc4VQxtiTKZM5/Q32IJsONoGP5ca0kWbYdubdcfaqFXP8P7yeRl3/fa7FrY2U7cmWdgY5vRDnREq8QqEafCVF3St8vI/sN2gmxg+AG7bLk2mLEPNXokJXvoE=
  - secure: YMfbl1wcLGJNe7Bg+Qr+xnlwFFNeTBZdKU3DtiRE4Fm5LO2yVGBKFJJOMM7sjFQbiNZv+h++XrvWLNCmFoTdbgrgwRTOm9JV6/nr6L2p78At//K9HgxPQ2441TdiNQtBzirzj3brk5mdsTP+7TKykpUCXw80gjCGaFFyq+TtfZyTLNFzZEqb9hspmI3IyCUsj2I08cSzdBokNOK9CB/Y60sbgnDGHgL9TWrxBWvWuAIXGgrnkB2f8P9m89J9jb0YSBMpPJXKejWrZfZSnBfQ0KfB+9AiEl+fV7j4zu28jnoukPdAfS4wkFkcUKSXO/ePw+PZv+Nqw70ReaoFNAukXYWMrzqa2K+x5Jx4exbSPvyFAn1N0xNDDwpUiCFjOnAmb4w/sKkzCv5HwB8S/yFxVDI1RqU2RXT1YNzRikUHje4HMbSXoDRIqaaqyp7NbjwZTSHV4ZXl0KkybqpE+5lwk+VGmwnq0iGb9JtwY4DwmDRP78w/qb4pckrEnYbVm2xw1muzNbjM6nJQ5WXfVIhmj3kFoK41tjmkZyquP6h7jwzLQ6zqT4Y11udIjQcda8vY7UkQLAIJOqDa6zFr71PpOyTjAVWNJUAuWhbrYnugNO20xGrXPBkY7zn3towrDPNA1MF9bVWIOnh1QAsgbahdVYOVg4vjHFjO2q8R36viWTw=
install:
- pip install -U poetry
- pip install -U tox-travis
script: tox
before-deploy:
- poetry config http-basic.mypypi $MYPYPI_USER $MYPYPI_PASS
- poetry build
deploy:
  provider: script
  script: poetry publish
  on:
    tags: true
    repo: jonaylor89/chronos
    branch: master
    python: 3.6
